# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_owning_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='log_reg.User'),
        ),
    ]
