# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desti', models.CharField(max_length=45)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_attendees', models.ManyToManyField(related_name='eventes_attending', to='log_reg.User')),
                ('event_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_owned', to='log_reg.User')),
            ],
        ),
    ]
